apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  template:
    spec:
      containers:
      - name: my-app
        image: perumal1804/springboot-app:3a0e473

        volumeMounts:
        - name: app-config-volume
          mountPath: /config
          readOnly: true

        env:
        - name: ENV
          value: dev

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD

        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"

      volumes:
      - name: app-config-volume
        configMap:
          name: app-config