apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../base
- externalsecret-app.yaml
- externalsecret-docker.yaml

generatorOptions:
  disableNameSuffixHash: true

patches:
- target:
    kind: Deployment
    name: my-app
  patch: |-
    - op: replace
      path: /metadata/name
      value: java-deployment

- target:
    kind: Service
    name: my-app
  patch: |-
    - op: replace
      path: /metadata/name
      value: java-service

- target:
    kind: PodDisruptionBudget
    name: my-app
  patch: |-
    - op: replace
      path: /metadata/name
      value: java-pdb

- path: deployment-patch.yaml 

# patches:
# - path: deployment-patch.yaml

# images:
# - name: docker.io/YOUR_USERNAME/YOUR_IMAGE
#   newTag: dev-latest

configMapGenerator:
- name: app-config
  files:
  - configmaps/app.properties